name: 新建 Releases（deepseek 帮写）

on:
  push:
    tags:
      - 'v*'  # 匹配 v 开头的标签，如 v1.0.0
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (格式 vX.X.X)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取全部提交历史

      - name: Get release tag
        id: get_tag
        run: |
          git clone https://github.com/toad114514/plugin.video.bilikodi ./src
          cd src
          # 推送标签触发时获取标签
          if [[ ${{ github.event_name }} == 'push' ]]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # 手动触发时使用输入值
            echo "TAG_NAME=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Get previous release tag
        id: get_previous_tag
        run: |
          # 获取按时间排序的上一个有效标签
          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=0 --max-count=1))
          
          if [ -z "$PREV_TAG" ]; then
            # 首次发布时获取首次提交
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "Previous tag: $PREV_TAG"

      - name: Generate changelog
        id: changelog
        run: |
          # 生成两次release间的提交日志
          echo "COMMITS=$(git log --pretty=format:"- %s (%h)" ${{ steps.get_previous_tag.outputs.PREV_TAG }}..${{ steps.get_tag.outputs.TAG_NAME }})" >> $GITHUB_OUTPUT

      - name: Create source zip
        run: |
          tar -czvf plugin.video.bilikodi.tar.gz .
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          name: ${{ steps.get_tag.outputs.TAG_NAME }}
          body: |
            ### Changes since ${{ steps.get_previous_tag.outputs.PREV_TAG }}
            ${{ steps.changelog.outputs.COMMITS }}
          files: |
            plugin.video.bilikodi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
